#!/usr/bin/env python3

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED_INSTRUCTIONS = REPO_ROOT / "agent-control-plane" / "project-instructions.md"
CANONICAL_SKILLS_DIR = REPO_ROOT / ".agents" / "skills"
CLAUDE_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
REQUIRED_SKILL = CANONICAL_SKILLS_DIR / "resetusb-change-gate" / "SKILL.md"

AGENT_DOCS = {
    "AGENTS.md": ".agents/skills/resetusb-change-gate/SKILL.md",
    "CLAUDE.md": ".claude/skills/resetusb-change-gate/SKILL.md",
    "GEMINI.md": ".agents/skills/resetusb-change-gate/SKILL.md",
}


def build_agent_doc(filename: str, skill_path: str, shared_body: str) -> str:
    header = [
        f"# {filename}",
        "",
        "This file is generated by `scripts/render-agent-control-plane.py`.",
        "Do not edit it manually. Edit `agent-control-plane/` or `.agents/skills/`, then rerender.",
        "",
        f"Agent-native change gate: `{skill_path}`",
        "",
        "",
    ]
    return "\n".join(header) + shared_body.rstrip() + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def collect_tree(root: Path) -> dict[str, bytes]:
    payload: dict[str, bytes] = {}
    if not root.exists():
        return payload

    for path in sorted(root.rglob("*")):
        if path.is_file():
            payload[str(path.relative_to(root))] = path.read_bytes()

    return payload


def expected_agent_docs() -> dict[Path, str]:
    shared_body = SHARED_INSTRUCTIONS.read_text(encoding="utf-8").strip() + "\n"
    payload: dict[Path, str] = {}
    for filename, skill_path in AGENT_DOCS.items():
        payload[REPO_ROOT / filename] = build_agent_doc(filename, skill_path, shared_body)
    return payload


def expected_claude_skill_payload() -> dict[str, bytes]:
    return collect_tree(CANONICAL_SKILLS_DIR)


def validate_canonical_inputs() -> None:
    if not SHARED_INSTRUCTIONS.is_file():
        raise FileNotFoundError(
            f"Missing shared instructions: {SHARED_INSTRUCTIONS.relative_to(REPO_ROOT)}"
        )

    if not REQUIRED_SKILL.is_file():
        raise FileNotFoundError(
            f"Missing canonical skill: {REQUIRED_SKILL.relative_to(REPO_ROOT)}"
        )

    if REQUIRED_SKILL.stat().st_size == 0:
        raise ValueError(
            f"Canonical skill is empty: {REQUIRED_SKILL.relative_to(REPO_ROOT)}"
        )


def render() -> list[Path]:
    validate_canonical_inputs()
    changed: list[Path] = []

    for path, content in expected_agent_docs().items():
        if write_if_changed(path, content):
            changed.append(path)

    if CLAUDE_SKILLS_DIR.exists():
        shutil.rmtree(CLAUDE_SKILLS_DIR)
    shutil.copytree(CANONICAL_SKILLS_DIR, CLAUDE_SKILLS_DIR)

    return changed


def check() -> int:
    errors: list[str] = []

    try:
        validate_canonical_inputs()
    except (FileNotFoundError, ValueError) as exc:
        errors.append(str(exc))

    for path, expected in expected_agent_docs().items():
        if not path.exists():
            errors.append(f"Missing generated file: {path.relative_to(REPO_ROOT)}")
            continue

        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"Out-of-date generated file: {path.relative_to(REPO_ROOT)}")

    expected_payload = expected_claude_skill_payload()
    actual_payload = collect_tree(CLAUDE_SKILLS_DIR)

    if actual_payload != expected_payload:
        errors.append("Claude skill mirror is out of sync with .agents/skills/")

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        print(
            "Run `python3 scripts/render-agent-control-plane.py` to regenerate the agent control plane.",
            file=sys.stderr,
        )
        return 1

    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render or verify the generated multi-agent control plane."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files instead of rewriting them.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.check:
        return check()

    changed = render()
    if changed:
        for path in changed:
            print(f"Updated {path.relative_to(REPO_ROOT)}")
    else:
        print("Agent documents already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
