name: ClusterFuzzLite Batch

on:
  schedule:
    - cron: "17 5 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  batch-fuzzing:
    name: batch-fuzzing
    runs-on: ubuntu-latest
    permissions:
      contents: read # Check out the repository and read fuzz targets from source.
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: c
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: c
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          mode: batch
